# Generated by Django 2.2 on 2019-04-04 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shorten_URL', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='short',
            field=models.IntegerField(null=True),
        ),
    ]
